# Generated by Django 4.2.1 on 2025-04-09 18:19

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_tracking',
            field=models.JSONField(default=tasks.models.Task.build_notification_tracking),
        ),
    ]
